# Generated by Django 4.2.1 on 2023-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Показать в меню'),
        ),
    ]
