# Generated by Django 4.2.1 on 2023-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_beer_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='photo',
            field=models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Company photo'),
        ),
    ]
