# Generated by Django 4.2.1 on 2023-05-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0007_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
